name: CI/CD Pipeline

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run Tests
        run: pytest --junitxml=report.xml

      - name: Save test report
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: report.xml

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create package
        run: |
          zip -r interference-dashboard.zip .

      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: app-package
          path: interference-dashboard.zip

  notify:
    needs: [test, build]
    runs-on: ubuntu-latest
    env:
      EMAIL_USER: ${{ secrets.EMAIL_USER }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      DEST_EMAIL: ${{ secrets.DEST_EMAIL }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Run notify script
        run: python scripts/send_email.py
